# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fytt2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 840)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 840))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 840))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(850, 10, 160, 692))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.multipliers_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.multipliers_layout.setObjectName(_fromUtf8("multipliers_layout"))
        self.cy3_ckbox = QtGui.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cy3_ckbox.setFont(font)
        self.cy3_ckbox.setObjectName(_fromUtf8("cy3_ckbox"))
        self.multipliers_layout.addWidget(self.cy3_ckbox)
        self.cy3_spin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.cy3_spin.setObjectName(_fromUtf8("cy3_spin"))
        self.multipliers_layout.addWidget(self.cy3_spin)
        self.cy3_slider = QtGui.QSlider(self.verticalLayoutWidget)
        self.cy3_slider.setMaximum(1000)
        self.cy3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cy3_slider.setObjectName(_fromUtf8("cy3_slider"))
        self.multipliers_layout.addWidget(self.cy3_slider)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem)
        self.cy5_ckbox = QtGui.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cy5_ckbox.setFont(font)
        self.cy5_ckbox.setObjectName(_fromUtf8("cy5_ckbox"))
        self.multipliers_layout.addWidget(self.cy5_ckbox)
        self.cy5_spin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.cy5_spin.setObjectName(_fromUtf8("cy5_spin"))
        self.multipliers_layout.addWidget(self.cy5_spin)
        self.cy5_slider = QtGui.QSlider(self.verticalLayoutWidget)
        self.cy5_slider.setMaximum(1000)
        self.cy5_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cy5_slider.setObjectName(_fromUtf8("cy5_slider"))
        self.multipliers_layout.addWidget(self.cy5_slider)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem1)
        self.bkg_ckbox = QtGui.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bkg_ckbox.setFont(font)
        self.bkg_ckbox.setObjectName(_fromUtf8("bkg_ckbox"))
        self.multipliers_layout.addWidget(self.bkg_ckbox)
        self.bkg_spin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.bkg_spin.setObjectName(_fromUtf8("bkg_spin"))
        self.multipliers_layout.addWidget(self.bkg_spin)
        self.bkg_slider = QtGui.QSlider(self.verticalLayoutWidget)
        self.bkg_slider.setMaximum(1000)
        self.bkg_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bkg_slider.setObjectName(_fromUtf8("bkg_slider"))
        self.multipliers_layout.addWidget(self.bkg_slider)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem2)
        self.offset_ckbox = QtGui.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.offset_ckbox.setFont(font)
        self.offset_ckbox.setObjectName(_fromUtf8("offset_ckbox"))
        self.multipliers_layout.addWidget(self.offset_ckbox)
        self.offset_spin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.offset_spin.setObjectName(_fromUtf8("offset_spin"))
        self.multipliers_layout.addWidget(self.offset_spin)
        self.offset_slider = QtGui.QSlider(self.verticalLayoutWidget)
        self.offset_slider.setMaximum(1000)
        self.offset_slider.setOrientation(QtCore.Qt.Horizontal)
        self.offset_slider.setObjectName(_fromUtf8("offset_slider"))
        self.multipliers_layout.addWidget(self.offset_slider)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem3)
        self.donor_shift_cbx = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.donor_shift_cbx.setChecked(True)
        self.donor_shift_cbx.setObjectName(_fromUtf8("donor_shift_cbx"))
        self.multipliers_layout.addWidget(self.donor_shift_cbx)
        self.donor_shift_spin = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.donor_shift_spin.setObjectName(_fromUtf8("donor_shift_spin"))
        self.multipliers_layout.addWidget(self.donor_shift_spin)
        self.acceptor_shift_cbx = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.acceptor_shift_cbx.setChecked(True)
        self.acceptor_shift_cbx.setObjectName(_fromUtf8("acceptor_shift_cbx"))
        self.multipliers_layout.addWidget(self.acceptor_shift_cbx)
        self.acceptor_shift_spin = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.acceptor_shift_spin.setObjectName(_fromUtf8("acceptor_shift_spin"))
        self.multipliers_layout.addWidget(self.acceptor_shift_spin)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem4)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.multipliers_layout.addWidget(self.label_5)
        self.fret_lbl = QtGui.QLabel(self.verticalLayoutWidget)
        self.fret_lbl.setObjectName(_fromUtf8("fret_lbl"))
        self.multipliers_layout.addWidget(self.fret_lbl)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.multipliers_layout.addWidget(self.label_7)
        self.err_lbl = QtGui.QLabel(self.verticalLayoutWidget)
        self.err_lbl.setObjectName(_fromUtf8("err_lbl"))
        self.multipliers_layout.addWidget(self.err_lbl)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(830, 10, 16, 731))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLine_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLine_layout.setObjectName(_fromUtf8("verticalLine_layout"))
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLine_layout.addWidget(self.line_2)
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 811, 491))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.plot_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.plot_layout.setObjectName(_fromUtf8("plot_layout"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 520, 811, 221))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.residual_layout = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.residual_layout.setObjectName(_fromUtf8("residual_layout"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(850, 700, 161, 41))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.autofitting_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.autofitting_layout.setObjectName(_fromUtf8("autofitting_layout"))
        self.autofit_btn = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.autofit_btn.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.autofit_btn.setObjectName(_fromUtf8("autofit_btn"))
        self.autofitting_layout.addWidget(self.autofit_btn)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 750, 1001, 57))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLine_layout = QtGui.QHBoxLayout()
        self.horizontalLine_layout.setObjectName(_fromUtf8("horizontalLine_layout"))
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLine_layout.addWidget(self.line)
        self.verticalLayout.addLayout(self.horizontalLine_layout)
        self.buttons_layout = QtGui.QHBoxLayout()
        self.buttons_layout.setObjectName(_fromUtf8("buttons_layout"))
        self.ref_btn = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ref_btn.setFont(font)
        self.ref_btn.setStyleSheet(_fromUtf8("background-color: rgb(244, 243, 40);"))
        self.ref_btn.setObjectName(_fromUtf8("ref_btn"))
        self.buttons_layout.addWidget(self.ref_btn)
        self.cy3_btn = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cy3_btn.setFont(font)
        self.cy3_btn.setStyleSheet(_fromUtf8("background-color: rgb(247, 132, 111);"))
        self.cy3_btn.setObjectName(_fromUtf8("cy3_btn"))
        self.buttons_layout.addWidget(self.cy3_btn)
        self.cy5_btn = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cy5_btn.setFont(font)
        self.cy5_btn.setStyleSheet(_fromUtf8("background-color: rgb(136, 171, 194);"))
        self.cy5_btn.setObjectName(_fromUtf8("cy5_btn"))
        self.buttons_layout.addWidget(self.cy5_btn)
        self.bkg_btn = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bkg_btn.setFont(font)
        self.bkg_btn.setStyleSheet(_fromUtf8("background-color: rgb(155, 155, 155);"))
        self.bkg_btn.setObjectName(_fromUtf8("bkg_btn"))
        self.buttons_layout.addWidget(self.bkg_btn)
        self.direct_emission_btn = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.direct_emission_btn.setFont(font)
        self.direct_emission_btn.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.direct_emission_btn.setObjectName(_fromUtf8("direct_emission_btn"))
        self.buttons_layout.addWidget(self.direct_emission_btn)
        self.loadBasisSets_btn = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loadBasisSets_btn.setFont(font)
        self.loadBasisSets_btn.setObjectName(_fromUtf8("loadBasisSets_btn"))
        self.buttons_layout.addWidget(self.loadBasisSets_btn)
        self.line_5 = QtGui.QFrame(self.widget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.buttons_layout.addWidget(self.line_5)
        self.save_btn = QtGui.QPushButton(self.widget)
        self.save_btn.setObjectName(_fromUtf8("save_btn"))
        self.buttons_layout.addWidget(self.save_btn)
        self.toolButton = QtGui.QToolButton(self.widget)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.buttons_layout.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.buttons_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionBatch_Fit = QtGui.QAction(MainWindow)
        self.actionBatch_Fit.setObjectName(_fromUtf8("actionBatch_Fit"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionBasis_Sets = QtGui.QAction(MainWindow)
        self.actionBasis_Sets.setObjectName(_fromUtf8("actionBasis_Sets"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.cy3_ckbox.setText(_translate("MainWindow", "Donor", None))
        self.cy5_ckbox.setText(_translate("MainWindow", "Acceptor", None))
        self.bkg_ckbox.setText(_translate("MainWindow", "Background", None))
        self.offset_ckbox.setText(_translate("MainWindow", "Offset", None))
        self.donor_shift_cbx.setText(_translate("MainWindow", "Donor Shift", None))
        self.acceptor_shift_cbx.setText(_translate("MainWindow", "Acceptor Shift", None))
        self.label_5.setText(_translate("MainWindow", "FRET Efficiency", None))
        self.fret_lbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">0.0</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "Error", None))
        self.err_lbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">0.0</span></p></body></html>", None))
        self.autofit_btn.setText(_translate("MainWindow", "Autofit Current Spectra", None))
        self.ref_btn.setText(_translate("MainWindow", "Reference", None))
        self.cy3_btn.setText(_translate("MainWindow", "Cy3 Basis", None))
        self.cy5_btn.setText(_translate("MainWindow", "Cy5 Basis", None))
        self.bkg_btn.setText(_translate("MainWindow", "Background Basis", None))
        self.direct_emission_btn.setText(_translate("MainWindow", "Direct Emission", None))
        self.loadBasisSets_btn.setText(_translate("MainWindow", "DB", None))
        self.save_btn.setText(_translate("MainWindow", "Save...", None))
        self.toolButton.setText(_translate("MainWindow", "A", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionBatch_Fit.setText(_translate("MainWindow", "Batch Fit...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionBasis_Sets.setText(_translate("MainWindow", "Basis Sets...", None))

