# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fytt2.ui'
#
# Created: Tue Apr 28 11:30:26 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 840)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 840))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 840))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 730, 1001, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.buttons_layout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttons_layout.setMargin(0)
        self.buttons_layout.setObjectName(_fromUtf8("buttons_layout"))
        self.ref_btn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.ref_btn.setStyleSheet(_fromUtf8("background-color: rgb(244, 243, 40);"))
        self.ref_btn.setObjectName(_fromUtf8("ref_btn"))
        self.buttons_layout.addWidget(self.ref_btn)
        self.cy3_btn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.cy3_btn.setStyleSheet(_fromUtf8("background-color: rgb(247, 132, 111);"))
        self.cy3_btn.setObjectName(_fromUtf8("cy3_btn"))
        self.buttons_layout.addWidget(self.cy3_btn)
        self.cy5_btn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.cy5_btn.setStyleSheet(_fromUtf8("background-color: rgb(136, 171, 194);"))
        self.cy5_btn.setObjectName(_fromUtf8("cy5_btn"))
        self.buttons_layout.addWidget(self.cy5_btn)
        self.bkg_btn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.bkg_btn.setStyleSheet(_fromUtf8("background-color: rgb(155, 155, 155);"))
        self.bkg_btn.setObjectName(_fromUtf8("bkg_btn"))
        self.buttons_layout.addWidget(self.bkg_btn)
        self.direct_emission_btn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.direct_emission_btn.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.direct_emission_btn.setObjectName(_fromUtf8("direct_emission_btn"))
        self.buttons_layout.addWidget(self.direct_emission_btn)
        self.loadBasisSets_btn = QtGui.QCommandLinkButton(self.horizontalLayoutWidget)
        self.loadBasisSets_btn.setMaximumSize(QtCore.QSize(50, 40))
        self.loadBasisSets_btn.setObjectName(_fromUtf8("loadBasisSets_btn"))
        self.buttons_layout.addWidget(self.loadBasisSets_btn)
        self.line_5 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.buttons_layout.addWidget(self.line_5)
        self.save_btn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.save_btn.setObjectName(_fromUtf8("save_btn"))
        self.buttons_layout.addWidget(self.save_btn)
        self.toolButton = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.buttons_layout.addWidget(self.toolButton)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(850, 10, 160, 692))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.multipliers_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.multipliers_layout.setMargin(0)
        self.multipliers_layout.setObjectName(_fromUtf8("multipliers_layout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.multipliers_layout.addWidget(self.label)
        self.cy3_spin = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.cy3_spin.setMinimum(1)
        self.cy3_spin.setMaximum(500000000)
        self.cy3_spin.setSingleStep(1000)
        self.cy3_spin.setObjectName(_fromUtf8("cy3_spin"))
        self.multipliers_layout.addWidget(self.cy3_spin)
        self.cy3_slider = QtGui.QSlider(self.verticalLayoutWidget)
        self.cy3_slider.setMaximum(1000)
        self.cy3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cy3_slider.setObjectName(_fromUtf8("cy3_slider"))
        self.multipliers_layout.addWidget(self.cy3_slider)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.multipliers_layout.addWidget(self.label_2)
        self.cy5_spin = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.cy5_spin.setMinimum(1)
        self.cy5_spin.setMaximum(500000000)
        self.cy5_spin.setSingleStep(1000)
        self.cy5_spin.setObjectName(_fromUtf8("cy5_spin"))
        self.multipliers_layout.addWidget(self.cy5_spin)
        self.cy5_slider = QtGui.QSlider(self.verticalLayoutWidget)
        self.cy5_slider.setMaximum(1000)
        self.cy5_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cy5_slider.setObjectName(_fromUtf8("cy5_slider"))
        self.multipliers_layout.addWidget(self.cy5_slider)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.multipliers_layout.addWidget(self.label_3)
        self.bkg_spin = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.bkg_spin.setMinimum(1)
        self.bkg_spin.setMaximum(500000000)
        self.bkg_spin.setSingleStep(1000)
        self.bkg_spin.setProperty("value", 1)
        self.bkg_spin.setObjectName(_fromUtf8("bkg_spin"))
        self.multipliers_layout.addWidget(self.bkg_spin)
        self.bkg_slider = QtGui.QSlider(self.verticalLayoutWidget)
        self.bkg_slider.setMaximum(1000)
        self.bkg_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bkg_slider.setObjectName(_fromUtf8("bkg_slider"))
        self.multipliers_layout.addWidget(self.bkg_slider)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem2)
        self.Offset = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.Offset.setObjectName(_fromUtf8("Offset"))
        self.multipliers_layout.addWidget(self.Offset)
        self.offset_spin = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.offset_spin.setMinimum(1)
        self.offset_spin.setMaximum(500000000)
        self.offset_spin.setSingleStep(1000)
        self.offset_spin.setObjectName(_fromUtf8("offset_spin"))
        self.multipliers_layout.addWidget(self.offset_spin)
        self.offset_slider = QtGui.QSlider(self.verticalLayoutWidget)
        self.offset_slider.setMaximum(1000)
        self.offset_slider.setOrientation(QtCore.Qt.Horizontal)
        self.offset_slider.setObjectName(_fromUtf8("offset_slider"))
        self.multipliers_layout.addWidget(self.offset_slider)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem3)
        self.donor_shift_cbx = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.donor_shift_cbx.setObjectName(_fromUtf8("donor_shift_cbx"))
        self.multipliers_layout.addWidget(self.donor_shift_cbx)
        self.donor_shift_spin = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.donor_shift_spin.setObjectName(_fromUtf8("donor_shift_spin"))
        self.multipliers_layout.addWidget(self.donor_shift_spin)
        self.acceptor_shift_cbx = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.acceptor_shift_cbx.setObjectName(_fromUtf8("acceptor_shift_cbx"))
        self.multipliers_layout.addWidget(self.acceptor_shift_cbx)
        self.accepto_shift_spin = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.accepto_shift_spin.setObjectName(_fromUtf8("accepto_shift_spin"))
        self.multipliers_layout.addWidget(self.accepto_shift_spin)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.multipliers_layout.addItem(spacerItem4)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.multipliers_layout.addWidget(self.label_5)
        self.fret_lbl = QtGui.QLabel(self.verticalLayoutWidget)
        self.fret_lbl.setObjectName(_fromUtf8("fret_lbl"))
        self.multipliers_layout.addWidget(self.fret_lbl)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.multipliers_layout.addWidget(self.label_7)
        self.err_lbl = QtGui.QLabel(self.verticalLayoutWidget)
        self.err_lbl.setObjectName(_fromUtf8("err_lbl"))
        self.multipliers_layout.addWidget(self.err_lbl)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 710, 1001, 20))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLine_layout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLine_layout.setMargin(0)
        self.horizontalLine_layout.setObjectName(_fromUtf8("horizontalLine_layout"))
        self.line = QtGui.QFrame(self.horizontalLayoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLine_layout.addWidget(self.line)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(830, 10, 16, 701))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLine_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLine_layout.setMargin(0)
        self.verticalLine_layout.setObjectName(_fromUtf8("verticalLine_layout"))
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLine_layout.addWidget(self.line_2)
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 811, 461))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.plot_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.plot_layout.setMargin(0)
        self.plot_layout.setObjectName(_fromUtf8("plot_layout"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 480, 811, 221))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.residual_layout = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.residual_layout.setMargin(0)
        self.residual_layout.setObjectName(_fromUtf8("residual_layout"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(850, 665, 171, 41))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.autofitting_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.autofitting_layout.setMargin(0)
        self.autofitting_layout.setObjectName(_fromUtf8("autofitting_layout"))
        self.autofit_btn = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.autofit_btn.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.autofit_btn.setObjectName(_fromUtf8("autofit_btn"))
        self.autofitting_layout.addWidget(self.autofit_btn)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 765, 751, 27))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ref_filename_lbl = QtGui.QLabel(self.horizontalLayoutWidget_3)

        self.ref_filename_lbl.setTextFormat(QtCore.Qt.RichText)
        self.ref_filename_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ref_filename_lbl.setWordWrap(False)
        self.ref_filename_lbl.setMargin(2)
        self.ref_filename_lbl.setObjectName(_fromUtf8("ref_filename_lbl"))
        self.horizontalLayout.addWidget(self.ref_filename_lbl)
        self.cy3_filename_lbl = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.cy3_filename_lbl.setMaximumSize(QtCore.QSize(145, 16777215))
        self.cy3_filename_lbl.setTextFormat(QtCore.Qt.RichText)
        self.cy3_filename_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cy3_filename_lbl.setWordWrap(False)
        self.cy3_filename_lbl.setMargin(2)
        self.cy3_filename_lbl.setObjectName(_fromUtf8("cy3_filename_lbl"))
        self.horizontalLayout.addWidget(self.cy3_filename_lbl)
        self.cy5_filename_lbl = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.cy5_filename_lbl.setMaximumSize(QtCore.QSize(145, 16777215))
        self.cy5_filename_lbl.setTextFormat(QtCore.Qt.RichText)
        self.cy5_filename_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cy5_filename_lbl.setWordWrap(False)
        self.cy5_filename_lbl.setMargin(2)
        self.cy5_filename_lbl.setObjectName(_fromUtf8("cy5_filename_lbl"))
        self.horizontalLayout.addWidget(self.cy5_filename_lbl)
        self.bkg_filename_lbl = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.bkg_filename_lbl.setMaximumSize(QtCore.QSize(145, 16777215))
        self.bkg_filename_lbl.setTextFormat(QtCore.Qt.RichText)
        self.bkg_filename_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bkg_filename_lbl.setWordWrap(False)
        self.bkg_filename_lbl.setMargin(2)
        self.bkg_filename_lbl.setObjectName(_fromUtf8("bkg_filename_lbl"))
        self.horizontalLayout.addWidget(self.bkg_filename_lbl)
        self.direct_emission_lbl = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.direct_emission_lbl.setMaximumSize(QtCore.QSize(145, 16777215))
        self.direct_emission_lbl.setTextFormat(QtCore.Qt.RichText)
        self.direct_emission_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.direct_emission_lbl.setWordWrap(False)
        self.direct_emission_lbl.setMargin(2)
        self.direct_emission_lbl.setObjectName(_fromUtf8("direct_emission_lbl"))
        self.horizontalLayout.addWidget(self.direct_emission_lbl)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionBatch_Fit = QtGui.QAction(MainWindow)
        self.actionBatch_Fit.setObjectName(_fromUtf8("actionBatch_Fit"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionBasis_Sets = QtGui.QAction(MainWindow)
        self.actionBasis_Sets.setObjectName(_fromUtf8("actionBasis_Sets"))
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionBatch_Fit)
        self.menuFile.addAction(self.actionBasis_Sets)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.ref_btn.setText(_translate("MainWindow", "Reference", None))
        self.cy3_btn.setText(_translate("MainWindow", "Cy3 Basis", None))
        self.cy5_btn.setText(_translate("MainWindow", "Cy5 Basis", None))
        self.bkg_btn.setText(_translate("MainWindow", "Background Basis", None))
        self.direct_emission_btn.setText(_translate("MainWindow", "Direct Emission", None))
        self.loadBasisSets_btn.setText(_translate("MainWindow", "DB", None))
        self.save_btn.setText(_translate("MainWindow", "Save...", None))
        self.toolButton.setText(_translate("MainWindow", "A", None))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Linear scaling factor for donor basis set</p></body></html>", None))
        self.label.setText(_translate("MainWindow", "Cy3 Multiplier", None))
        self.label_2.setText(_translate("MainWindow", "Cy5 Multiplier", None))
        self.label_3.setText(_translate("MainWindow", "Background Multiplier", None))
        self.Offset.setText(_translate("MainWindow", "Constrain Offset", None))
        self.donor_shift_cbx.setText(_translate("MainWindow", "Donor Shift", None))
        self.acceptor_shift_cbx.setText(_translate("MainWindow", "Acceptor Shift", None))
        self.label_5.setText(_translate("MainWindow", "FRET Efficiency", None))
        self.fret_lbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">0.0</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "Error", None))
        self.err_lbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">0.0</span></p></body></html>", None))
        self.autofit_btn.setText(_translate("MainWindow", "Autofit Current Spectra", None))
        self.ref_filename_lbl.setText(_translate("MainWindow", "TextLabel", None))
        self.cy3_filename_lbl.setText(_translate("MainWindow", "TextLabel", None))
        self.cy5_filename_lbl.setText(_translate("MainWindow", "TextLabel", None))
        self.bkg_filename_lbl.setText(_translate("MainWindow", "TextLabel", None))
        self.direct_emission_lbl.setText(_translate("MainWindow", "TextLabel", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionBatch_Fit.setText(_translate("MainWindow", "Batch Fit...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionBasis_Sets.setText(_translate("MainWindow", "Basis Sets...", None))

