# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basis.ui'
#
# Created: Wed Apr 22 19:27:14 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BasisGui(object):
    def setupUi(self, BasisGui):
        BasisGui.setObjectName(_fromUtf8("BasisGui"))
        BasisGui.resize(800, 770)
        BasisGui.setMinimumSize(QtCore.QSize(800, 770))
        BasisGui.setMaximumSize(QtCore.QSize(800, 770))
        BasisGui.setMouseTracking(False)
        self.layoutWidget = QtGui.QWidget(BasisGui)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 330, 761, 23))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.namesLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.namesLayout.setMargin(0)
        self.namesLayout.setObjectName(_fromUtf8("namesLayout"))
        self.donor_lbl = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.donor_lbl.setFont(font)
        self.donor_lbl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.donor_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.donor_lbl.setObjectName(_fromUtf8("donor_lbl"))
        self.namesLayout.addWidget(self.donor_lbl)
        self.acceptor_lbl = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.acceptor_lbl.setFont(font)
        self.acceptor_lbl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.acceptor_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.acceptor_lbl.setObjectName(_fromUtf8("acceptor_lbl"))
        self.namesLayout.addWidget(self.acceptor_lbl)
        self.background_lbl = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.background_lbl.setFont(font)
        self.background_lbl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.background_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.background_lbl.setObjectName(_fromUtf8("background_lbl"))
        self.namesLayout.addWidget(self.background_lbl)
        self.horizontalLayoutWidget = QtGui.QWidget(BasisGui)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 629, 741, 20))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_1 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setMargin(0)
        self.horizontalLayout_1.setObjectName(_fromUtf8("horizontalLayout_1"))
        self.line = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_1.addWidget(self.line)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(BasisGui)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 700, 741, 16))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.line_2 = QtGui.QFrame(self.horizontalLayoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.layoutWidget1 = QtGui.QWidget(BasisGui)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 668, 761, 33))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.wavelengthLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.wavelengthLayout.setMargin(0)
        self.wavelengthLayout.setObjectName(_fromUtf8("wavelengthLayout"))
        self.donorExcitation_spin = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.donorExcitation_spin.setMinimum(1.0)
        self.donorExcitation_spin.setMaximum(1400.0)
        self.donorExcitation_spin.setObjectName(_fromUtf8("donorExcitation_spin"))
        self.wavelengthLayout.addWidget(self.donorExcitation_spin)
        self.line_3 = QtGui.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.wavelengthLayout.addWidget(self.line_3)
        self.acceptorExcitation_spin = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.acceptorExcitation_spin.setMinimum(1.0)
        self.acceptorExcitation_spin.setMaximum(1400.0)
        self.acceptorExcitation_spin.setObjectName(_fromUtf8("acceptorExcitation_spin"))
        self.wavelengthLayout.addWidget(self.acceptorExcitation_spin)
        self.line_4 = QtGui.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.wavelengthLayout.addWidget(self.line_4)
        self.spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.wavelengthLayout.addWidget(self.spinBox)
        self.layoutWidget2 = QtGui.QWidget(BasisGui)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 390, 761, 151))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.tablesLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.tablesLayout.setMargin(0)
        self.tablesLayout.setObjectName(_fromUtf8("tablesLayout"))
        self.donor_list = QtGui.QTableView(self.layoutWidget2)
        self.donor_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.donor_list.setMouseTracking(True)
        self.donor_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.donor_list.setObjectName(_fromUtf8("donor_list"))
        self.tablesLayout.addWidget(self.donor_list)
        self.acceptor_list = QtGui.QTableView(self.layoutWidget2)
        self.acceptor_list.setObjectName(_fromUtf8("acceptor_list"))
        self.tablesLayout.addWidget(self.acceptor_list)
        self.background_list = QtGui.QTableView(self.layoutWidget2)
        self.background_list.setObjectName(_fromUtf8("background_list"))
        self.tablesLayout.addWidget(self.background_list)
        self.layoutWidget3 = QtGui.QWidget(BasisGui)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 648, 761, 23))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.wavelengthLabelLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.wavelengthLabelLayout.setMargin(0)
        self.wavelengthLabelLayout.setObjectName(_fromUtf8("wavelengthLabelLayout"))
        self.donorEx_lbl = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.donorEx_lbl.setFont(font)
        self.donorEx_lbl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.donorEx_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.donorEx_lbl.setObjectName(_fromUtf8("donorEx_lbl"))
        self.wavelengthLabelLayout.addWidget(self.donorEx_lbl)
        self.acceptorEx_lbl = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.acceptorEx_lbl.setFont(font)
        self.acceptorEx_lbl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.acceptorEx_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.acceptorEx_lbl.setObjectName(_fromUtf8("acceptorEx_lbl"))
        self.wavelengthLabelLayout.addWidget(self.acceptorEx_lbl)
        self.slitWidth_lbl = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slitWidth_lbl.setFont(font)
        self.slitWidth_lbl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.slitWidth_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.slitWidth_lbl.setObjectName(_fromUtf8("slitWidth_lbl"))
        self.wavelengthLabelLayout.addWidget(self.slitWidth_lbl)
        self.layoutWidget4 = QtGui.QWidget(BasisGui)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 598, 761, 33))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.loadLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.loadLayout.setMargin(0)
        self.loadLayout.setObjectName(_fromUtf8("loadLayout"))
        self.correctionFactor_cbx = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.correctionFactor_cbx.setFont(font)
        self.correctionFactor_cbx.setObjectName(_fromUtf8("correctionFactor_cbx"))
        self.loadLayout.addWidget(self.correctionFactor_cbx)
        self.correctionFactor_spin = QtGui.QDoubleSpinBox(self.layoutWidget4)
        self.correctionFactor_spin.setObjectName(_fromUtf8("correctionFactor_spin"))
        self.loadLayout.addWidget(self.correctionFactor_spin)
        self.line_5 = QtGui.QFrame(self.layoutWidget4)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.loadLayout.addWidget(self.line_5)
        self.lamp_lbl = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lamp_lbl.setFont(font)
        self.lamp_lbl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lamp_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lamp_lbl.setObjectName(_fromUtf8("lamp_lbl"))
        self.loadLayout.addWidget(self.lamp_lbl)
        self.lamp_box = QtGui.QComboBox(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lamp_box.sizePolicy().hasHeightForWidth())
        self.lamp_box.setSizePolicy(sizePolicy)
        self.lamp_box.setMinimumSize(QtCore.QSize(200, 0))
        self.lamp_box.setObjectName(_fromUtf8("lamp_box"))
        self.loadLayout.addWidget(self.lamp_box)
        self.addLamp = QtGui.QToolButton(self.layoutWidget4)
        self.addLamp.setObjectName(_fromUtf8("addLamp"))
        self.loadLayout.addWidget(self.addLamp)
        self.deleteLamp = QtGui.QToolButton(self.layoutWidget4)
        self.deleteLamp.setObjectName(_fromUtf8("deleteLamp"))
        self.loadLayout.addWidget(self.deleteLamp)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(BasisGui)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 578, 741, 20))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.line_7 = QtGui.QFrame(self.horizontalLayoutWidget_3)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_3.addWidget(self.line_7)
        self.layoutWidget5 = QtGui.QWidget(BasisGui)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 356, 761, 33))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.filterLayout = QtGui.QHBoxLayout(self.layoutWidget5)
        self.filterLayout.setMargin(0)
        self.filterLayout.setObjectName(_fromUtf8("filterLayout"))
        self.donor_filter = QtGui.QLineEdit(self.layoutWidget5)
        self.donor_filter.setMinimumSize(QtCore.QSize(226, 0))
        self.donor_filter.setToolTip(_fromUtf8(""))
        self.donor_filter.setText(_fromUtf8(""))
        self.donor_filter.setObjectName(_fromUtf8("donor_filter"))
        self.filterLayout.addWidget(self.donor_filter)
        self.acceptor_filter = QtGui.QLineEdit(self.layoutWidget5)
        self.acceptor_filter.setMinimumSize(QtCore.QSize(226, 0))
        self.acceptor_filter.setObjectName(_fromUtf8("acceptor_filter"))
        self.filterLayout.addWidget(self.acceptor_filter)
        self.background_filter = QtGui.QLineEdit(self.layoutWidget5)
        self.background_filter.setMinimumSize(QtCore.QSize(226, 0))
        self.background_filter.setObjectName(_fromUtf8("background_filter"))
        self.filterLayout.addWidget(self.background_filter)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(BasisGui)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(19, 19, 761, 301))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.previewLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.previewLayout.setMargin(0)
        self.previewLayout.setObjectName(_fromUtf8("previewLayout"))
        self.gridLayoutWidget = QtGui.QWidget(BasisGui)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 540, 761, 31))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.deleteAcceptor = QtGui.QToolButton(self.gridLayoutWidget)
        self.deleteAcceptor.setObjectName(_fromUtf8("deleteAcceptor"))
        self.gridLayout.addWidget(self.deleteAcceptor, 0, 4, 1, 1)
        self.deleteBackground = QtGui.QToolButton(self.gridLayoutWidget)
        self.deleteBackground.setObjectName(_fromUtf8("deleteBackground"))
        self.gridLayout.addWidget(self.deleteBackground, 0, 7, 1, 1)
        self.addAcceptor = QtGui.QToolButton(self.gridLayoutWidget)
        self.addAcceptor.setObjectName(_fromUtf8("addAcceptor"))
        self.gridLayout.addWidget(self.addAcceptor, 0, 3, 1, 1)
        self.deleteDonor = QtGui.QToolButton(self.gridLayoutWidget)
        self.deleteDonor.setObjectName(_fromUtf8("deleteDonor"))
        self.gridLayout.addWidget(self.deleteDonor, 0, 1, 1, 1)
        self.addDonor = QtGui.QToolButton(self.gridLayoutWidget)
        self.addDonor.setObjectName(_fromUtf8("addDonor"))
        self.gridLayout.addWidget(self.addDonor, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.addBackground = QtGui.QToolButton(self.gridLayoutWidget)
        self.addBackground.setObjectName(_fromUtf8("addBackground"))
        self.gridLayout.addWidget(self.addBackground, 0, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(BasisGui)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 720, 761, 44))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.setDirectExcitation_btn = QtGui.QCommandLinkButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setDirectExcitation_btn.setFont(font)
        self.setDirectExcitation_btn.setObjectName(_fromUtf8("setDirectExcitation_btn"))
        self.horizontalLayout.addWidget(self.setDirectExcitation_btn)
        self.sendBasisSetsToMain_btn = QtGui.QCommandLinkButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sendBasisSetsToMain_btn.setFont(font)
        self.sendBasisSetsToMain_btn.setObjectName(_fromUtf8("sendBasisSetsToMain_btn"))
        self.horizontalLayout.addWidget(self.sendBasisSetsToMain_btn)

        self.retranslateUi(BasisGui)
        QtCore.QMetaObject.connectSlotsByName(BasisGui)

    def retranslateUi(self, BasisGui):
        BasisGui.setWindowTitle(_translate("BasisGui", "Form", None))
        self.donor_lbl.setText(_translate("BasisGui", "Donor Basis Sets", None))
        self.acceptor_lbl.setText(_translate("BasisGui", "Acceptor Basis Sets", None))
        self.background_lbl.setText(_translate("BasisGui", "Background Basis Sets", None))
        self.donorExcitation_spin.setToolTip(_translate("BasisGui", "Excitation wavelength for donor emission", None))
        self.acceptorExcitation_spin.setToolTip(_translate("BasisGui", "Excitation wavelength for collecting only the acceptor spectra", None))
        self.spinBox.setToolTip(_translate("BasisGui", "Slit Width for the measurement", None))
        self.donor_list.setToolTip(_translate("BasisGui", "List of Donor basis sets. Select a donor to load the corresponding basis set for fitting", None))
        self.acceptor_list.setToolTip(_translate("BasisGui", "List of acceptor basis sets. Select an acceptor to load the corresponding basis set for fitting", None))
        self.background_list.setToolTip(_translate("BasisGui", "List of background basis sets. Select a background to load the corresponding basis set for fitting", None))
        self.donorEx_lbl.setText(_translate("BasisGui", "Donor Excitation", None))
        self.acceptorEx_lbl.setText(_translate("BasisGui", "Acceptor Excitation", None))
        self.slitWidth_lbl.setText(_translate("BasisGui", "Slit Width", None))
        self.correctionFactor_cbx.setText(_translate("BasisGui", "Manual Correction Factor", None))
        self.lamp_lbl.setText(_translate("BasisGui", "Choose Lamp Spectra", None))
        self.lamp_box.setToolTip(_translate("BasisGui", "Select the lamp used for collecting fluorescence spectra", None))
        self.addLamp.setText(_translate("BasisGui", "+", None))
        self.deleteLamp.setText(_translate("BasisGui", "-", None))
        self.donor_filter.setPlaceholderText(_translate("BasisGui", " Filter Donor Basis Sets", None))
        self.acceptor_filter.setPlaceholderText(_translate("BasisGui", " Filter Acceptor Basis Sets", None))
        self.background_filter.setPlaceholderText(_translate("BasisGui", " Filter Background Basis Sets", None))
        self.deleteAcceptor.setText(_translate("BasisGui", "-", None))
        self.deleteBackground.setText(_translate("BasisGui", "-", None))
        self.addAcceptor.setText(_translate("BasisGui", "+", None))
        self.deleteDonor.setText(_translate("BasisGui", "-", None))
        self.addDonor.setText(_translate("BasisGui", "+", None))
        self.addBackground.setText(_translate("BasisGui", "+", None))
        self.setDirectExcitation_btn.setToolTip(_translate("BasisGui", "Set the calculated direct excitation correction factor into the fitting window", None))
        self.setDirectExcitation_btn.setText(_translate("BasisGui", "Set Excitation Correction Factor (0.00)", None))
        self.sendBasisSetsToMain_btn.setText(_translate("BasisGui", "Send Basis Sets to Fytt", None))

